htdir = /var/www/localhost/htdocs
all:
	echo "Nothing to do"

install:
	install -m755 -o apache -d ${htdir}; \
	install -m755 -o apache -t ${htdir} \
	 xray.html config.php post.php last.php gixos.html \
		post-gixos.php gixos-last.php ;\



